### ISSUE TITLE
Wrong url on publication entries

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#10]
See https://www.computationalpathologygroup.eu/publications/bult19a/ I think this happens when the url-tag is kept empty in the bib file. 

@ghumpire could you take a look at this?

**Comment by ghumpire** [comment]
Issue fixed, this was a conflict of tags. Pelican defines by default the tag page.url for every page, I was using the same tag to show the URL of the publication. I changed page.url to page.urlweb for publications to avoid future conflicts.

Now the following publications are correct:
- Publication without URL link: https://www.computationalpathologygroup.eu/publications/bult19a/
- Publication with URL link: https://www.computationalpathologygroup.eu/publications/bokh18a/

Closing this issue.
