### ISSUE TITLE
Computational Pathology Group hardcoded

### ISSUE THREAD

**Issue by jonasteuwen** [DIAGNijmegen/website-content#100]
E.g.: radboudumc-template/templates/software.html
radboudumc-template/templates/calendar-archive.html
radboudumc-template/templates/thesis-gallery.html
radboudumc-template/templates/home.html

Also, aiimnijmegen.nl still has 'Computational Pathology' in some of the links, e.g. when posting something on Twitter.

**Comment by wouterbulten** [comment]
I've updated the pages. Do you have an example of a page that does not work when sharing on social media?

**Comment by jonasteuwen** [comment]
@wouterbulten The changes that have been made seem to have fixed the issue. When I shared the main page
