### ISSUE TITLE
More dynamic home page image

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#101]
Based on comments in #90 and #84. 

We can experiment with ways to make the home page image more dynamic. For example, we could use the image of the first highlight. This would require no further content work from the groups.

**Comment by MeykeHermsen** [comment]
Very good idea, I like it

**Comment by wouterbulten** [comment]
You can now set the home image to 'highlight' mode, and the jumbotron itself to 'dense'. This results in a dynamic and smaller top frame:

![image](https://user-images.githubusercontent.com/2886251/63009607-1f813500-be85-11e9-91a5-ac4b113e3521.png)
