### ISSUE TITLE
Order publications 

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#102]
The publications are currently not ordered in the publication list (except by year and type). 

For example, the first five listed journal papers of the CP group are from April 10, April 15, June 10, January 29 and the 1rst of March. 

We should decide if we want the month to be read from the bibentry, which tag we use for this and after that I can check/correct all the DIAG publications.

**Comment by wouterbulten** [comment]
@martvanrijthoven can you take a look at this?

**Comment by wouterbulten** [comment]
See #151

**Comment by wouterbulten** [comment]
@martvanrijthoven you already completed this, right?

**Comment by martvanrijthoven** [comment]
Almost, i need to test it when the bib file is fixed (waiting for an update from coen)

**Comment by martvanrijthoven** [comment]
@coendevente  do you have any updates about the month tag in the bib file?

**Comment by coendevente** [comment]
> @coendevente do you have any updates about the month tag in the bib file?

Haven't been able to do this yet. I'll try to have it finished by next week. What would be the preferred format for the month tag, again?

**Comment by martvanrijthoven** [comment]
preferred is month: number, but another solution will probably also be fine. Thanks in advance!

**Comment by bramvanginneken** [comment]
I do not want month in diag publications. It’s often absent and most journals do not add it in their references

**Comment by martvanrijthoven** [comment]
@bramvanginneken ok i understand. Do you have any preference for how the publications should be sorted aside from the year and the type?

**Comment by coendevente** [comment]
In diag.bib and diagnoweb.bib there already are entries with a month tag. Doesn't it depend on the template whether they will be displayed in publications? Or should the month tags be removed from the bib files?

**Comment by bramvanginneken** [comment]
Latex/bibtex style files determine if this is included. It's ok to leave it, I would not display it on the DIAG website, diagnijmegen.nl does not do it. Exceptio is PhD thesis, there I prefer a full date (but it's a detail)

**Comment by coendevente** [comment]
@martvanrijthoven you would still like to have all items in `diag.bib` to have a - consistent - month tag for ordering, not for display, right?

**Comment by martvanrijthoven** [comment]
Yes for ordering if would be great, do you think it is possible? Based on the comment from Bram, I realized that it may be a hassle to keep track of the months, especially retrospective. I think it would be nice to sort by month if a consistent month tag is available for every publication.

**Comment by coendevente** [comment]
Yes I think it would be a lot of work to find the months for all publications, as most of them don't have this information in the bib file. But I can take a look if I can maybe use some APIs to retrieve this information automatically for the bulk of all entries.

**Comment by coendevente** [comment]
@martvanrijthoven I've made all month tags consistent in `diag.bib`. They're now all a month number without leading zero.

Also, I've added new month tags to 737 items (going from 120 to 857). I used the Crossref and arXiv APIs for this (see [processbib.py](https://github.com/DIAGNijmegen/diag-literature/blob/master/processbib.py) for the implementation). I used the doi, arXiv ID, and titles and author names to get the publication dates. Now there still are 592 items left without month tag, so I will see if I can find other ways to get the month tags for those.

**Comment by bramvanginneken** [comment]
Nice Coen. Could be good to use these APIs to do some other checks too. I assume they add a month when the final version appears and not the in press or online month? These things are quite confusing these days.

**Comment by martvanrijthoven** [comment]
Thanks Coen!

**Comment by coendevente** [comment]
Would indeed be nice to do additional checks. The Crossref API also has page and issue numbers, so that might also be intersting to use to do some checks. Do you have any other suggestions? [This](https://api.crossref.org/v1/works/10.1056/NEJMoa1911793) is an example output of the api.

About the dates and to which versions they correspond, for arXiv papers, I'm using the `published` value that the API gives and for papers that are in Crossref, I use the `issued` value. For a handful of papers I checked with the websites on which they were published whether the APIs gave the same months and that seemed to be correct.

**Comment by martvanrijthoven** [comment]
sorting will be done via pmid.

**Comment by martvanrijthoven** [comment]
the publications ae now sorted via pmid.
