### ISSUE TITLE
display videos

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#104]
I want to be able to show a video on a page using a markdown command. In mediawiki it works like this:

We introduce the project with a BBC report on a big health care project in Ghana, where a large number of hospitals are equipped with digital x-ray and our CAD4TB software:

{#ev:youtube|-YVozBT5HaA}

Can that be added?

**Comment by AjayPatel86** [comment]
I found some info on this. Apparently Markdown does not officially support video embeddings but you can embed raw HTML in it. The following are instructions for a work around I found:

1. Go to the Video page on YouTube and click on the Share Button
2. Choose Embed
3. Copy and Paste the HTML snippet in your markdown

The snippet looks like:

    <iframe width="560" height="315"
src="https://www.youtube.com/embed/MUQfKFzIOeU" 
frameborder="0" 
allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
allowfullscreen></iframe>

I will test this.

**Comment by wouterbulten** [comment]
I've added support for youtube movies. See for example:

https://www.computationalpathologygroup.eu/highlights/radboud_science_award_2018/

The embed code works as follows:

`[youtube: 9ks7cLpYAw8]`

It generates HTML that auto-scales so that it also works on mobile devices. It also uses the no-cookie domain of youtube.

**Comment by bramvanginneken** [comment]
Thanks! Can you support other sites besides youtube too? I also use vimeo to place my own movies.

**Comment by wouterbulten** [comment]
Yes, we can add practically any video site that supports embedding. I've added support for vimeo:

`[vimeo: <video id>]`

Let me know if we need to support other sites as well.
