### ISSUE TITLE
Links in the list of members returns 404

### ISSUE THREAD

**Issue by ghumpire** [DIAGNijmegen/website-content#107]
**Describe the bug**
It seems something is wrong with the slugs. See https://www.computationalpathologygroup.eu/members/ and click on any member, it will redirect to a 404 page. 

**To Reproduce (if applicable)**
1. Go to Members section (https://www.computationalpathologygroup.eu/members/)
2. Click on the link of any member
3. See error: 404!

**Additional context**
I noticed this happens on the CP website and the Retina group, the RSE website seems to be fine. In the Members list, Francesco's link should be: https://www.computationalpathologygroup.eu/members/francesco-ciompi/ but it points to https://www.computationalpathologygroup.eu/members/members/francesco-ciompi/

Similar behavior on the Projects page, see People section of https://www.computationalpathologygroup.eu/projects/deeppca/.

**Comment by ghumpire** [comment]
Vacancies page were not affected. See https://www.computationalpathologygroup.eu/vacancies/deep-learning-for-the-differentiation-of-stic-lesions/

**Comment by wouterbulten** [comment]
I was working on the member links and for some time the links were not correct. They should work now :)

Let me know if you think I missed something!
