### ISSUE TITLE
Retina - Change structure Projects page

### ISSUE THREAD

**Issue by CristinaGGonzalo** [DIAGNijmegen/website-content#11]
Is it possible to swap the order of the titles to: 
Current research projects
Software
?

**Comment by wouterbulten** [comment]
Do you want this feature as you don't have any software yet? Because we can also hide the header if there are no software pages.

**Comment by CristinaGGonzalo** [comment]
We would like just to change order, since we also plan to include our workstation in the website under Software, but we wanted to give priority to the Current research projects.

**Comment by wouterbulten** [comment]
Changed the order. Maybe in the future we can make this configurable.
