### ISSUE TITLE
How to refer to other page on our site?

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#119]
For example in Rita Bijlsma's bio there is a sentence where 'the deep learning cluster'. This should be replaced by the word Sol and be a reference to our page on Sol. How to do that? Of course I can give a hard link to the url of the rse site, which will probably break in the future. Can I refer to the Sol md page on https://github.com/DIAGNijmegen/website-content/blob/master/content/pages/software/sol.md?

(This page is in a folder called software, that is also weird...)

**Comment by jonasteuwen** [comment]
Related: #93

**Comment by martvanrijthoven** [comment]
We can build a short link (like with videos and members) for other page types.

**Comment by wouterbulten** [comment]
I've juist built a version of this system, we can test it now for projects, vacancies, software, people, and presentations. To account for the new links, the syntax of the old links have changed. Examples:

```
[software/asap]

[vacancy/deep-learning-for-artifacts]

[project/deeppca]

[presentation/unsupervised-prostate-cancer-detection]
```

**Comment by wouterbulten** [comment]
Still todo: Links should default to the website the link is on (if that page exist). Unless, the group: tag is set. This reduces cross-site navigation.

**Comment by wouterbulten** [comment]
Fixed. See https://github.com/DIAGNijmegen/website-content/blob/master/docs/special-content-tags.md for documentation on this new feature.
