### ISSUE TITLE
General- missing publications (double last names connected with -)

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#12]
When people have a double last name connected with a -, these publications do not appear in their personal publication list.

**Comment by ghumpire** [comment]
Publications of Zaneta Swiderska-Chadaj are now listed, you can compare it with the old DIAG website:
- Pathology website https://www.computationalpathologygroup.eu/publications/zaneta-swiderska-chadaj/ 
- Old DIAG website: http://diagnijmegen.nl/index.php/PublicationsAuthor?author=Z._Swiderska-Chadaj&fullname=Zaneta+Swiderska-Chadaj
