### ISSUE TITLE
Wrong link in Publications "Back to page of..'

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#125]
In the publication list of all people with accents in their name (Péter, Clarisa and Cristina) the link 'Go back to page of...' does not work. This link directs to https://beta.diagnijmegen.nl/members/péter-bándi/ while the original page is called https://beta.diagnijmegen.nl/members/peter-bandi/. 
The .md file is written with accents though.

**Comment by martvanrijthoven** [comment]
It seems that the problem is due the foldername of a member e.g:
https://github.com/DIAGNijmegen/website-pathology/tree/master/members/peter-bandi

I am not sure if we are in control of making this folder or if this is automated

**Comment by wouterbulten** [comment]
The link is generated by the template here:

https://github.com/DIAGNijmegen/website-content/blob/master/radboudumc-template/templates/publications-author.html#L9

It's based on the name of the person. We should strip special characters and then the link should work.
