### ISSUE TITLE
could you add support for slideshare?

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#129]
it would be nice if we can show slides, if there is some other system for doing that that's also fine.

**Comment by wouterbulten** [comment]
Yes we can do that. As far as I can see, slideshare as an easy to implement embed code.

In theory, any service that allows embedding we can built support for.

**Comment by wouterbulten** [comment]
Is there an example that we can test this with? And maybe the page where we should show this?

**Comment by martvanrijthoven** [comment]
Added slideshare support which can be used as follows:

[slideshare: slidesharekey] 

If custom styling is needed, the iframe code can also be used directly.
 (e.g: <iframe src="//www.slideshare.net/slideshow/embed_code/key/7dIwzX8sWUvlab" width="595" height="485" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/adamnash/be-a-great-product-leader-amplify-oct-2019" title="Be A Great Product Leader (Amplify, Oct 2019)" target="_blank">Be A Great Product Leader (Amplify, Oct 2019)</a> </strong> de <strong><a href="https://www.slideshare.net/adamnash" target="_blank">Adam Nash</a></strong> </div>)
