### ISSUE TITLE
Pathology - Request highlight section home page

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#13]
1. It would be nice if we could add a button after the highlights on the homepage that says: ' All highlights', that redirects you to the Highlight page (also requested by Francesco).

2. I would like it if we could write a short caption about the highlight in the overview page, that has a fixed number of characters. Now the text in de boxes has a different size and it just shows the first lines of the original article.

**Comment by MeykeHermsen** [comment]
3. Maybe we can go up to 3 highlights on the home page

**Comment by martvanrijthoven** [comment]
- (1) All highlights button added to the homepage.
- (2) this is already possible with the 'description' tag. However, there is no fixed number of characters (not sure if this is needed now?)

**Comment by MeykeHermsen** [comment]
I was not aware that the description tag worked here as well; I am working on adding this for all highlights
