### ISSUE TITLE
Thesis Clarisa does not appear

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#136]
Although her name is written similar as in her publications, her thesis does not appear

**Comment by martvanrijthoven** [comment]
The thesis from clarisa now shows up. 

However the other thesis (from other people) currently on diagnijmegen listed under her name as well are not showing up. However this is for example also the case for Geert https://www.computationalpathologygroup.eu/publications/geert-litjens/) vs http://www.diagnijmegen.nl/index.php/PublicationsAuthor?author=G._Litjens&fullname=Geert+Litjens.

**Comment by martvanrijthoven** [comment]
closing this issue, opening new one for other thesis
