### ISSUE TITLE
External link from AI for Health website not correct

### ISSUE THREAD

**Issue by KDercksen** [DIAGNijmegen/website-content#140]
See https://github.com/DIAGNijmegen/website-content/pull/132, support for both external/past members.

On the [MIHRacle](https://www.ai-for-health.nl/projects/mihracle/) page, my name now links to https://www.ai-for-health.nl/www.linkedin.com/in/koen-dercksen-083a835b/ instead of just the LinkedIn URL.

**Comment by wouterbulten** [comment]
You had a typo in the url (https:/ vs https://) which results in browsers prepending the site url.

**Comment by KDercksen** [comment]
Woops.. Thanks!
