### ISSUE TITLE
Adding multiple images on projects page does not work

### ISSUE THREAD

**Issue by HarmvZ** [DIAGNijmegen/website-content#15]
I tried to add 2 images to my project page, but only the first one is showing. In the URL for the second image the `{filename}` part is not parsed.

See [here](https://rse.diagnijmegen.nl/projects/ophthalmology_workstation/) for an example.

**Comment by wouterbulten** [comment]
You had a typo in the filename. `{filename}` is only parsed when the file exists. I've fixed it for the page.

**Comment by HarmvZ** [comment]
Ah, thanks!
