### ISSUE TITLE
People links on AI for Health link to beta.diagnijmegen.nl

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#152]
On the project pages on the AI for Health website, clicking on the name of a DIAG-affiliated person leads to their profile on beta.diagnijmegen.nl instead of the profile on diagnijmegen.nl

For example: https://www.ai-for-health.nl/vacancies/msc-muscle-fat-segmentation/

![image](https://user-images.githubusercontent.com/773597/74239358-fcbac680-4cd7-11ea-9d78-c8c385baaf74.png)

Since AI for Health is live and the new DIAG website is not, this seems like a bug to me.

**Comment by wouterbulten** [comment]
In essence it works as intended, within the system the beta website _is_ the correct diag website and there is no info to link to the old site. What we can do for now is disable the links to diag persons that do not have a live group website.

**Comment by wouterbulten** [comment]
I've linked diag people to the old website based on name matching.
