### ISSUE TITLE
Add email to external-people.yaml

### ISSUE THREAD

**Issue by AjayPatel86** [DIAGNijmegen/website-content#153]
Is it possible to add an extra line to each entry of the external people directory for their email address? 

Ideally this would then show as a mailto envelope button under their name on the AI for Health project webpages. Something like this:

![contact](https://user-images.githubusercontent.com/15669173/74423234-331b5180-4e50-11ea-9dc3-93d868a7194a.jpg)

**Comment by wouterbulten** [comment]
I've added support for email. See for example https://www.ai-for-health.nl/projects/mihracle/

**Comment by AjayPatel86** [comment]
Is it possible to also add this function for people who are not on the external_people list but are members? For example: https://www.ai-for-health.nl/projects/pneumothorax/ does not show the button for DIAG members.

**Comment by wouterbulten** [comment]
Email for group members can now be configured. I've enabled it for the AI for health website.
