### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#154]
In old system, two items were added to the news.xls to make announcements: 
-..will defend his/her thesis at..
- .. successfully defended his/her theses
Both messages could be hidden until or after a certain date. Now this has to be done manually, which will probably lead to outdated info on the page as this is easy to forget. Perhaps we could only show future events?

**Comment by wouterbulten** [comment]
Implemented this. To make this work you can set the following tags:

```
content_before: (before the date)
content_aftetr: (after the date)
```

See https://beta.diagnijmegen.nl/calendar/ for an example. The auto build should pick this up in the future (but we will have to check if it does).
