### ISSUE TITLE
Size tiles theses gallery

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#157]
All tiles in the theses gallery should have the same size.

**Comment by wouterbulten** [comment]
@MeykeHermsen I think you specifically mean the same height?

**Comment by MeykeHermsen** [comment]
Yes

**Comment by wouterbulten** [comment]
We can probably set a max height on each image. Additionally, we should probably alter the sizing for mobile views.

**Comment by wouterbulten** [comment]
I've updated the card size for small (mobile) devices. Regarding the height: we cannot really do this without sacrificing the layout. The underlying images have different aspect ratios. If we try to set a certain height then either the columns won't match up or the thesis covers are cut off. 

This will be a won't fix unfortunately. Luckily, the top of each row and the columns do match.
