### ISSUE TITLE
arXiv issues

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#159]
- Replace ARXIV with arXiv on the publication page
- For Article bibentries, the URL entry is originally intended for arXiv links. Is it possible to only show arXiv when this is filled in? So no more URL links in the paper overview?
- The arXiv links are missing in the preprints while this section is specifically for arXiv papers.

**Comment by martvanrijthoven** [comment]
replaced ARXIV with arXiv
no more URL links
added arXiv links
