### ISSUE TITLE
Add ability to view people that are not in the group

### ISSUE THREAD

**Issue by HarmvZ** [DIAGNijmegen/website-content#16]
I added James and Clarisa to my project while James is not in the retina group and Clarisa is not in the RSE group. This results in their picture and job title not showing up on those pages. It would be nice if it does show that, although I understand this might be difficult since you don't want those people to be shown as members of the group.

Example: [this](https://rse.diagnijmegen.nl/projects/ophthalmology_workstation/) vs. [this](https://www.a-eyeresearch.nl/projects/ophthalmology_workstation/)

**Comment by wouterbulten** [comment]
A quick fix would be to show the image. Showing other information (and potentially linking to their profile) is a bit harder.

**Comment by HarmvZ** [comment]
Showing the picture would be nice I think. Although I would give this issue a low priority, because it's a such a minor detail.

**Comment by wouterbulten** [comment]
Project pages now also show images for people from other groups.
