### ISSUE TITLE
Journal names go wrong 

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#161]
Sometimes Journal names go wrong while they are listed correctly in diag.bib, fullstring.bib and medlinestring.bib. Example: leem19b

**Comment by martvanrijthoven** [comment]
this is fixed

**Comment by martvanrijthoven** [comment]
The journal names are not correctly parsed, again.

**Comment by martvanrijthoven** [comment]
fixed

**Comment by bramvanginneken** [comment]
Great! I saw an unparsed diacritical sign in a conference name: Bildverarbeitung f\"ur die Medizin. Can you turn on parsing in journal and conference names?

**Comment by martvanrijthoven** [comment]
Thanks for spotting that! It should be fixed now.
