### ISSUE TITLE
PDF support with missing PDFs

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#162]
Not all bibentries (need to) have a PDF. Currently, when a PDF is requested and missing, the user receives an email like normal while getting an error when clicking on the link. It would be good if somewhere earlier in the process it's mentioned that no PDF is available.

**Comment by wouterbulten** [comment]
There was some debug code left in the template. Mart can you check if the papers also outputs this correctly?

**Comment by martvanrijthoven** [comment]
Looks like it is resolved after the debug code was removed.
