### ISSUE TITLE
Url of publication changing cannonical url

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#174]
See this publication item:

https://github.com/DIAGNijmegen/website-pathology/blob/d38e9ff1184535b5cd104bf45e1a52c770e17ade/publications/ciom12a/index.html

The cannonical URL is incorrectly set (as "http://www.cvc.uab.es/?p=361"). This results in crawl errors. As far as I can see, the only possibility of this occurring is when the publication md file has the 'url' tag set. This tag is reserved for pelican and should not be used for publication pages. Instead we could use something like pub_url.

**Comment by martvanrijthoven** [comment]
Removed  the url tag from the md files. Not sure if this has solved it.

**Comment by wouterbulten** [comment]
Yes it did. See https://github.com/DIAGNijmegen/website-pathology/blob/master/publications/ciom12a/index.html

Closing the issue. Thanks!
