### ISSUE TITLE
Create former employee page for DIAG

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#191]
This page should merge both custom content (the old list on diagnijmegen.nl) with an automatically generated list.

**Comment by wouterbulten** [comment]
Add some documentation regarding former employees.

**Comment by wouterbulten** [comment]
For DIAG there is now a former employee page, see https://beta.diagnijmegen.nl/former-employees/ This pages merges custom content with the auto-generated list.

@MeykeHermsen do you have some time to write a new documentation page on how we handle former employees? i.e. that we don't delete the page but change the `active` variable.

**Comment by wouterbulten** [comment]
One thing left to do is to cross-check the two lists, some names are now mentioned twice.

**Comment by bramvanginneken** [comment]
On the former employees page I want only linkedin pages as on the current site.

**Comment by wouterbulten** [comment]
The rationale of keeping the people pages is to prevent dead links. People often link to their page and the people pages are one of the most searched pages in google. Of course we can choose to not link to these pages on the former employee page.

Would you prefer to keep the pages, but only show the Linkedin page on the "former employee page"? We can do that automatically as people should fill in their linkedin on their page. Their linkedin will then automatically be added to the list when their page is updated to inactive.

**Comment by bramvanginneken** [comment]
The page could just list the link to LinkedIn or any other url. No text (or just Former Employee, but that's also not correct for eg studients/visitors), no picture. I'm sure it will otherwise contain outdated information. We'd still need to check the linkedin pages, I did this for the list on diagnijmegen.nl

**Comment by wouterbulten** [comment]
Todo: Auto-generate a list of Linkedin pages on the former employee page.

**Comment by martvanrijthoven** [comment]
Will not make employee page for diag, people should be added manually for DIAG
