### ISSUE TITLE
Alert mechanism for invalid bib items.

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#195]
See https://beta.diagnijmegen.nl/publications/

**Comment by wouterbulten** [comment]
Skip publication when year was not set and trigger a warning.

**Comment by martvanrijthoven** [comment]
This is fixed. bib items with no year will be printed to console. Would be great if we think of a mechanism that alerts us. However  when the diag.bib validation script is ready it may not be necessary. I keep this issue open for discussion but will set it to low priority.
