### ISSUE TITLE
Move/Remove fading cards Research page

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#199]
Bram would like the fading lower or not to be there at all. In case of the latter, set need agreements on aspect ratio and resolution.

**Comment by wouterbulten** [comment]
We are going to do a test with new images (2:1 width/height ratio) and without using fade in the cards.

**Comment by wouterbulten** [comment]
The new images should also link to the correct page.

**Comment by MeykeHermsen** [comment]
We agreed to remove the fading. When all project images ares adjusted to 2:1 ratio, I will turn it off.

**Comment by MeykeHermsen** [comment]
Adjusted for all websites except ai for health.

**Comment by wouterbulten** [comment]
@MeykeHermsen I have made the card gradients opt-in for now. Should we add some documentation regarding the new image dimensions?

**Comment by MeykeHermsen** [comment]
Yes, I will add that. Perhaps we should set the minimum width to 300 px as well, what do you think? The tumorbudding picture is 160 and too low quality.

**Comment by wouterbulten** [comment]
At least 480 would be nice, that's a bit bigger than the card width.
