### ISSUE TITLE
set size of embedded movies

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#202]
**Is your feature request related to a problem? Please describe.**
https://github.com/DIAGNijmegen/website-content/blob/master/docs/special-content-tags.md explains how to add a youtube movie. Usually these embed things have options, eg to make the movie smaller, add buttons etc, if that is possible, could this be added?

**Describe the solution you'd like**

**Additional context (Optional)**

**Comment by martvanrijthoven** [comment]
Hi Bram,

In the markdown file you can add the embedded code for a youtube video directly (you can get this code via the share button on youtube) e.g.,

<iframe width="560" height="315" src="https://www.youtube.com/embed/PPLop4L2eGk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

In this code, you can adjust all kinds of settings. 

Would this be acceptable, or do you want specific options to be configured via the special youtube tag?
