### ISSUE TITLE
Computational Pathology Group is hardcoded into open graph/twitter meta info

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/website-content#22]
Here: https://github.com/DIAGNijmegen/website-content/blob/master/radboudumc-template/templates/base.html

Results in this in slack when sharing a page from rse.diagnijmegen.nl:
![Screenshot_20190405_135835](https://user-images.githubusercontent.com/12661555/55626125-f3ed9000-57aa-11e9-9bca-e8d07e410490.png)

**Comment by wouterbulten** [comment]
Should be fixed now. Just make sure to set the correct settings in pelicanconf.py.
