### ISSUE TITLE
Check publications consistency with diagnijmegen

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#229]
We have to check the publication list consistency with the old website. 

- For example extracting the bib keys from http://diagnijmegen.nl/index.php/PublicationsAuthor?author=B._van_Ginneken&fullname=Bram+van+Ginneken&yearheadings=0 with ~~JSON.stringify(Array.from(document.querySelectorAll("a[bibkey]")).map(a => a.getAttribute('bibkey'))~~
JSON.stringify(Array.from(document.querySelectorAll("span[name]")).map(a => a.getAttribute('name')))
(thanks Wouter).
- ADD Accepted or to appear (see opt tag)

**Comment by martvanrijthoven** [comment]
I checked the bib keys with the old website and the new website. 
All bibkey are present on the new website + 53 publications that were not in the old website:

here is the list:

{'abas05a','arnt15','arzh07a','arzh07b','garc06','gatt09','ginn01','ginn05','ginn05a','ginn07a','ginn08c','herm20','hoop08','hoop08a','hoop09a','horn04','horn04a','isgu03a','isgu05a','isgu09a','kall15a','lohn15','lope03','mend07a','mend09b','mend15a','mich20','murp08b','murp09a','niem03b','niem05','poza06','prok03a','rads11','riep02','roel04','samu08a','sanc06a','scha10b','schi03a','schi05a','slui02','slui03a','timp02','uden15','uffm05b','vos07','vos08a','vos14c','wals00','wand15a','wand15b','wand15c'}

I am not sure why they are not on the old website.

**Comment by bramvanginneken** [comment]
Do you mean diagnijmegen.nl with the old website. Abas05a is listed there and Arzh07a:
![image](https://user-images.githubusercontent.com/1818749/89528534-7cd76a00-d7eb-11ea-89c4-b6eb76d82690.png)

**Comment by martvanrijthoven** [comment]
Thank Bram, i understand now why i did not get these bibkeys. It think it is because the list of 'missing' publications are not having an individual page on diagnijmegen, that's why the JSON.stringfy doesn't extract these publications. Wouter has updated the JSON.stringfy command and i will compute the differences again.

**Comment by martvanrijthoven** [comment]
After running the difference script again the following publications are not found on diagnijmegen.nl
{'bult20a', 'herm20', 'riep20', 'scha10b', 'uffm05b'}
