### ISSUE TITLE
Migrate diagnijmegen websites linked in about page to new website

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#239]
There are some links to pages in the about page of beta.diagnijmegen (https://beta.diagnijmegen.nl/about/) which refer to diagnijmegen links because these pages do not exist yet (e.g., http://diagnijmegen.nl/index.php/CAD4TB) . These pages should be migrated to the new website and the links in the about page should be updated.

**Comment by bramvanginneken** [comment]
I’ve updated the page and all links should now work. Do you have a tool to check all links on the entire website? That’s useful, we used such a tool it for diagnijmegen.nl. Where can I see an overview of broken links?

**Comment by martvanrijthoven** [comment]
Thanks for updating the about page! We do not have such a tool (there is no overview at the moment), but this would be indeed nice to have. Maybe we can use a pelican plugin that checks it every build (something like this https://github.com/silentlamb/pelican-deadlinks/)
