### ISSUE TITLE
Customizable css for each website

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#240]
~Implement publication page version without grayish background, and with 100% black letters and with open sans as font.~

Implement css customization options for each individual website

**Comment by bramvanginneken** [comment]
No sorry I meant this for the entire site. I do not like it that all the different websites look identical. I’d like to experiment with changes to the overall stylesheet of diagnijmegen vs computationalpathology.

**Comment by wouterbulten** [comment]
Also required for retina website.

**Comment by wouterbulten** [comment]
We have a basic implementation for this now. Each website can have custom css rules on top of the base template.
