### ISSUE TITLE
Links to members with a special character don't seem to work

### ISSUE THREAD

**Issue by GeertLitjens** [DIAGNijmegen/website-content#247]
**Describe the bug**

If you type [member/geert-litjens] a link to my page will appear. However, it does not seem to work if there is a special character in the name: [member/clarisa-sánchez]

**To Reproduce (if applicable)**
Check the About page

**Comment by wouterbulten** [comment]
Pelican saves all slugs as ASCII so people pages should also have ASCII filenames to allow for linking.
