### ISSUE TITLE
Staff listed on AI for Health pages

### ISSUE THREAD

**Issue by AjayPatel86** [DIAGNijmegen/website-content#249]
On the AI for Health [meeting page:](https://www.ai-for-health.nl/meeting/) it is now showing Scientifc Staff at the bottom of the page. It only lists Jasper van der Graaf for some reason. It is also the case on the [About ](https://www.ai-for-health.nl/about/)and [Courses ](https://www.ai-for-health.nl/courses/)pages.

![image](https://user-images.githubusercontent.com/15669173/90642959-52e26680-e233-11ea-88b6-91ad9173f39d.png)

**Comment by wouterbulten** [comment]
This is not a bug luckily. The page has the 'people' template so it renders the page with all the people that have set ai-for-health as their group. To make it a normal page you can remove the template tag all together so it renders as a default page.

**Comment by AjayPatel86** [comment]
I have turned them all into default pages and it has fixed the issue.
