### ISSUE TITLE
Deploy all websites to Netlify

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#253]
All websites are moved to Netlify:

- [x] DIAG
- [x] CPG
- [x] Retina
- [x] RSE
- [x] RTC
- [ ] AIIM
- [x] AI for Health

**Comment by martvanrijthoven** [comment]
uploaded the zip of AIIM wbsite to Netlify (commit: 8c6de5f433e60f7b1a335c1c42e33f368b76f25d)
emailed Jonas  if he can change the CNAME and A-Record. 
uploaded API key to travis for AIIM website

TODO
- change .travis settings when Jonas emails back with confirmation

**Comment by wouterbulten** [comment]
AIIM is not used anymore, so all websites have now been migrated. Great work Mart! (Last thing, could you remove AIMM from Netlify?)
