### ISSUE TITLE
"About" page does not have an icon on the DIAG page

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#257]
When viewing the DIAG page on a small screen, the navigation shows the icons, but the "About" page is missing one:

![image](https://user-images.githubusercontent.com/773597/91017730-e975a580-e5ee-11ea-9abb-480ff9455ab5.png)

On medium sized screens, only the icons are shown, so the "About" page is then not accessible.

**Comment by martvanrijthoven** [comment]
Thanks for the bug report! This is fixed now.
