### ISSUE TITLE
AI for health home page restructering

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#264]
- [ ] Vacancies in cards
- [ ] PhD projects in cards (with fixed max number, active only)
- [ ] Master projects in cards (with fixed max number, active only)

**Comment by wouterbulten** [comment]
We will build support for custom home page templates.

**Comment by wouterbulten** [comment]
Todo: Take a look at Pelican base templates.

**Comment by AjayPatel86** [comment]
> * [ ]  Vacancies in cards
> * [ ]  PhD projects in cards (with fixed max number, active only)
> * [ ]  Master projects in cards (with fixed max number, active only)

You can remove the bottom two tasks. Vacancies in cards is the only request for now.

**Comment by martvanrijthoven** [comment]
Will make global vacancies as cards
