### ISSUE TITLE
Custom cards on RTC page to link to subpages

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#265]
A list of cards on top of the page. E.g. a card "What is deep learning?"

**Comment by AjayPatel86** [comment]
Any update on when this request can be handled?

**Comment by martvanrijthoven** [comment]
Hi Ajay, I am not sure, to be honest. Wouter and I are currently the only webteam members (and Wouter is almost finishing his PhD). So we have to prioritize issues. 

@wouterbulten  could you maybe explain a bit more what needs to be done here and then you can put it under my name.

I will check if can find some time to implement it this week or maybe next week.

**Comment by wouterbulten** [comment]
I think it's easiest to just make a custom home page template for RTC. Then maybe Ajay can also experiment with the layout/content.

**Comment by martvanrijthoven** [comment]
@wouterbulten  thanks for the suggestion!

@AjayPatel86 , I found a relatively clean way to create a custom homepage template. It involves a couple of (easy) steps so maybe it is best if i show you. of course, i can help you create the custom template. Can we have a short meeting today or tomorrow?
