### ISSUE TITLE
News item for Hans' publication on PAMI

### ISSUE THREAD

**Issue by kiranvaidhya** [DIAGNijmegen/website-content#266]
Opening this issue to write a news item on Hans' recent publication in PAMI on [Streaming convolutional neural networks for end-to-end learning with multi-megapixel images](https://ieeexplore.ieee.org/document/9178453)

Images provided by Hans:
# Image1
![Screenshot from 2020-08-31 11-26-16](https://user-images.githubusercontent.com/10166968/91848988-a0ab9580-ec5b-11ea-8479-fe15cfe05f8c.png)
# Image2
![Screenshot from 2020-08-31 11-27-11](https://user-images.githubusercontent.com/10166968/91848994-a4d7b300-ec5b-11ea-8b14-49ccd912e9dc.png)
# Image3
![Screenshot from 2020-08-31 11-27-48](https://user-images.githubusercontent.com/10166968/91849001-a903d080-ec5b-11ea-9737-42da63b74677.png)

**Comment by kiranvaidhya** [comment]
So I write a news piece for Hans' work on Streaming CNNs, but none of the images get rendered on my local build. What was the solution for this? @wouterbulten I remember this issue being open here #232, and that the images need to be copied from the images folder, right? Can you maybe give me a short snippet that copies the images onto the right paths?

![image](https://user-images.githubusercontent.com/10166968/91869734-84692200-ec76-11ea-932b-181925552b60.png)

**Comment by bramvanginneken** [comment]
Go to https://www.diagnijmegen.nl/news/defense-maschenka-balkenhol/, click edit, I think you see an example there

**Comment by wouterbulten** [comment]
For local testing, you can copy the full image folder to 'website-diag/content/images'.

**Comment by kiranvaidhya** [comment]
Hi @wouterbulten, do you want to review and merge the pull request?
