### ISSUE TITLE
Add default bootstrap classes to generated output

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#27]
See #26  as mentioned by @pkcakeout 

We should automatically add bootstrap classes to elements (like table). Something like https://github.com/ingwinlu/pelican-bootstrapify would be a nice fit.

**Comment by pkcakeout** [comment]
Ha! Wow, that was quick! Thanks for fixing!

**Comment by wouterbulten** [comment]
First implementation is live. Some tweaks to improve styling are still to be done.
