### ISSUE TITLE
Design tweaks for main design

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#278]
Issue to continue discussions of #276

**Comment by wouterbulten** [comment]
@HansPinckaers could you check the comments by @bramvanginneken in #276 and see if they are resolved now. @martvanrijthoven also did some work on the publication list. Would be nice to merge the design soon!

**Comment by HansPinckaers** [comment]
| Segoe UI | Arial |
| -----------| ----- |
| ![Screenshot from 2020-09-24 14-50-49](https://user-images.githubusercontent.com/70747/94147353-77a2ad00-fe75-11ea-9f88-f8e5bc79ad5f.png) | ![Screenshot from 2020-09-24 14-50-38](https://user-images.githubusercontent.com/70747/94147359-7a050700-fe75-11ea-80ea-b2102cfd1652.png) |

I propose we remove Segoe from the font-family list. The contrast between normal text and bold is just too much. It has multiple weight options, but those are not compatible with other webfonts.

**Comment by HansPinckaers** [comment]
Actually with the new font-weight in PR #286 Segoe looks okay as well.

**Comment by HansPinckaers** [comment]
I think we can close this issue right?

**Comment by wouterbulten** [comment]
Yes :)
