### ISSUE TITLE
Add multiple positions to DIAG member profile

### ISSUE THREAD

**Issue by njmhendrix** [DIAGNijmegen/website-content#285]
**Describe the bug**
Besides being an associate professor, Matthieu Rutten is a radiologist as well. He wants to add multiple positions to his profile on the DIAG website. Thus, I added "radiologist" to his profile (content/pages/members/matthieu-rutten.md) using this line "position: Associate Professor, Radiologist" (see commit #284). This text is properly displayed on the people page (https://www.diagnijmegen.nl/people/), but not on a vacancy page (https://www.ai-for-health.nl/vacancies/fracture-detection-radius-ulna-metacarpals/). On the latter page, the text is displayed as a list (see screenshots).

**To Reproduce**
To reproduce the behaviour, add multiple positions to the "position" field in a biography markdown file (located at content/pages/members/) using commas as separators. 

**Screenshots**
<img width="153" alt="people_page" src="https://user-images.githubusercontent.com/47858231/93876316-f1e8fb00-fcd6-11ea-844c-37551d4232e7.PNG">
Appearance on people page.  

<img width="434" alt="vacancy_page" src="https://user-images.githubusercontent.com/47858231/93876331-f57c8200-fcd6-11ea-8e05-2bbeb0a56471.PNG">
Appearance on vacancy page (MSc project).

**Comment by njmhendrix** [comment]
I applied a quick fix for this issue by changing the text line to "position: Associate Professor and Radiologist". I still think it would be nice to be able to use commas, so that's why I haven't closed this issue yet.

**Comment by martvanrijthoven** [comment]
TODO for mart: check if quotation marks will solve it
