### ISSUE TITLE
Publications from former members are not copied to their former group

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#298]
When a member md file is removed or changed and the group tag is not present or without a value,
publications for this author are not copied to the group anymore.

This might be a problem for former members of diag, for which we still want to show their publications on the website.
We could fix this by keeping the member md file and adding a former_group tag.

**Comment by martvanrijthoven** [comment]
create a publication configuration yaml file which includes names of external/former authors

**Comment by nlessmann** [comment]
Is this still an issue? The current workaround is to no delete the .md file when someone leaves but only set their status to inactive?

**Comment by nlessmann** [comment]
Instructions not to delete the member page have been added to the documentation.
