### ISSUE TITLE
Update the former employees pages

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#3]
Redesign/reformulate the former employee page.

**Comment by wouterbulten** [comment]
I suggest removing the "x is a former employee" text. Instead we can just show the bio. When somebody leaves diag we can update their bio to represent this, like "x finished her master thesis in august 2017". @MeykeHermsen what do you think?

**Comment by MeykeHermsen** [comment]
I agree, maybe something like this for master students?:  "person defended his/her thesis titled "x" and has obtained his/her master's degree at x." (this is now the text for Marjolijn and Jim for instance)
And for bachelor (HLO) students: "person successfully completed his/her internship, titled "x"."

Do you have a proposal for former technical staff?

**Comment by wouterbulten** [comment]
What do you think of leaving the bio but appending this information? Or would you prefer to remove it?

Regarding technical staff, maybe something like: "x worked as a analist/etc. in our group until April 2019"?

**Comment by MeykeHermsen** [comment]
Sure, we can also add it. Sounds good.
