### ISSUE TITLE
Booktitle Swid20d is not parsed

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#305]
The booktitle of Swid20d is parsed as CPEE, which is the string. The string is defined in diag.bib and fullstrings.bib. As there is no medline abbreviation, not in medline.bib. Could you check why this happens?

**Comment by martvanrijthoven** [comment]
I could not find the entry in fullstrings.bib, so i added this line:
@String { _IEEE_International_Conference_on_Computational_Problems_of_Electrical_Engineering_ = {IEEE International Conference on Computational Problems of Electrical Engineering}}

Also, in diag.bib the entry was as follows:
@String{CPEE              = _IEEE_International_Conference_on_Computational_Problems_of_Electrical_Engineering_}
 i changed it to :
@string{CPEE = _IEEE_International_Conference_on_Computational_Problems_of_Electrical_Engineering_}

(note the change @String -> @string) 

It seems it is parsed now correctly:
https://www.diagnijmegen.nl/publications/swid20d/
