### ISSUE TITLE
Thesis Gallery on diagnijmegen

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#307]
- ~~Auto generator thesis fronts from pdf]~~
- [x] Change thesis gallery to show more ima- ges in a row on desktop viewports  
- [x] Find solution for different sized thesis images (could be fixed manually)
- [x] Fix all older thesis images
- [x] Update docs on how to add thesis to thesis gallery

**Comment by martvanrijthoven** [comment]
Auto-generating thesis front is problematic due to various sizes of front pages and various starting points of front pages. 
Possible solution is that thesis-owners/supervisors will upload front image in a specific format.

**Comment by martvanrijthoven** [comment]
we will divide the theses without cover and download and extract the thesis image. Next, we will divide all images and make them similar-sized. Lastly, we will have to update the docs such that users can add their thesis to the gallery themselves.

**Comment by nlessmann** [comment]
Jasper will check how many images (thesis covers) have a different format and whether it is easy to automatically crop them all to the same size.

**Comment by nlessmann** [comment]
I've checked the images in `content/images/theses` and computed an average aspect ratio. Then I've added a script (`crop_thesis_covers.py`) that automatically crops images to that aspect ratio if needed. This has also been added to the image optimization pipeline, so thesis covers that are added in the future should be automatically cropped.

**Comment by nlessmann** [comment]
Looks nice, but many are missing or don't have a cover: https://www.diagnijmegen.nl/thesis-gallery/

**Comment by JasperLinmans** [comment]
Final TODOs:
* Show bram / decide to make it accessible on the main website of diagnijmegen.nl
* Update the docs on TRAC to make sure that PhD students upload their cover in the GitHub folder.
