### ISSUE TITLE
Add links for publons and orcid

### ISSUE THREAD

**Issue by bramvanginneken** [DIAGNijmegen/website-content#321]
I changed my profile page, adding these lines:

scholar: http://scholar.google.com/citations?user=O1j6_MsAAAAJ
publons: https://publons.com/researcher/2761863/bram-van-ginneken/
orcid: https://orcid.org/0000-0003-2028-8972
linkedin: http://www.linkedin.com/in/bramvanginneken/

I removed the researcherid line as that has now moved to publons. And I added orcid as this seems to have become a widely used standard with many journals asking you to provide your orcid. Could you add support so that publons and orcid are shown like scholar, and Linkedin? Should we also support twitter or is nobody active on twitter in diag?

**Comment by martvanrijthoven** [comment]
Publons and Orcid are now implemented. I also added twitter in case anybody once to use it
