### ISSUE TITLE
Make separate header for ArXiv-only papers

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#33]
Currently, ArXiV papers are placed under ' Paper in International Journal' on the website. Perhaps we can make a separate header for ArXiv papers?

**Comment by ghumpire** [comment]
You are right, this is something I have to change in the publications pipeline. Will work on it next week.

**Comment by ghumpire** [comment]
See preprints section:
- General list:
    - https://www.computationalpathologygroup.eu/publications/
    - https://www.a-eyeresearch.nl/publications/
- Publications per author:
   - https://www.computationalpathologygroup.eu/publications/wouter-bulten/
   - https://www.computationalpathologygroup.eu/publications/geert-litjens/
