### ISSUE TITLE
Thesis images are incorrectly sized

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#331]
See for example: https://www.diagnijmegen.nl/publications/jaco15b/

We need to make sure that the thesis images do not take up the full width on desktop viewports. Relevant template:

https://github.com/DIAGNijmegen/website-content/blob/master/radboudumc-template/templates/publication-thesis.html#L11

**Comment by martvanrijthoven** [comment]
Use news template for thesis page (check full-width/normal width, use normal width)
