### ISSUE TITLE
deploy-master geeft bug bij het automatisch deployen

### ISSUE THREAD

**Issue by PhoenixYseven** [DIAGNijmegen/website-content#353]
**Describe the bug**
Bij de automatische deploy treed bug op. Zie error logs.
Oplossing is de versie van python naar 3.9 te zetten.

Groeten,
Rob

**Comment by martvanrijthoven** [comment]
Thanks for the bug report and solution! I have downgraded pip from 21.1 to 21.0.1, which for now also solves the problem. To update python i first need to run some tests. Keeping this issue open until I updated to python3.9.
