### ISSUE TITLE
Picture Micael Karlberg

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#371]
Hi Mart,

Micael Karlberg initially gave a picture which was already cropped in a circle. This resulted in a black rim around his picture on the website. I have updated the picture yesterday (it is still round but I pasted it on a white square), yet the picture hasn't changed on the website. Can you help out? Thanks!

**Comment by martvanrijthoven** [comment]
Thanks for creating the new image!

You added the new image to content/images instead of content/images/people. I have moved the file and it looks good now.
