### ISSUE TITLE
List peoples software on their detail page

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/website-content#41]
At the moment peoples projects are listed on their detail page (eg, https://www.computationalpathologygroup.eu/members/geert-litjens/). It would be nice if their software could also be listed.

**Comment by ghumpire** [comment]
This issue is fixed. See:
- Software section https://rse.diagnijmegen.nl/members/james-meakin/
- Projects section https://www.computationalpathologygroup.eu/members/geert-litjens/

**Comment by jmsmkn** [comment]
Thanks!

**Comment by cjacobs1** [comment]
Awesome!
