### ISSUE TITLE
Review publication list

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#439]
There are always publications listed on the website with issues, like missing journal names. We need to review this list on a regular basis and ideally add more automatic checks to the diag-literature repository.

**Comment by keelinm** [comment]
Joey and I discussed that if a publication is listed as @MastersThesis then the text (Masters Thesis) should appear in place of a journal name (to make it clear) and similarly for @phdthesis items- (PhD Thesis)

**Comment by keelinm** [comment]
Joey completed this with a fix in the literature repo
