### ISSUE TITLE
Option to add personal website to people page

### ISSUE THREAD

**Issue by GeertLitjens** [DIAGNijmegen/website-content#44]
Might be nice to let people specify their personal website in addition to Scholar/LinkedIn

**Comment by wouterbulten** [comment]
Should be fairly easy to implement. Just need to decide on an icon ;)

**Comment by GeertLitjens** [comment]
No big preference, I checked in FontAwesome, but they didn't have a great icon

**Comment by wouterbulten** [comment]
You can add your personal website with `website: ....` on your member page.
