### ISSUE TITLE
Get notification/email when builds fail

### ISSUE THREAD

**Issue by JoeySpronck** [DIAGNijmegen/website-content#443]
We now need to check our selves or get notified by others

**Comment by nlessmann** [comment]
I've added a step to the GitHub actions build process that *should*  run when the build fails. It doesn't do anything yet, but we can check until next week whether it works as expected.

For sending notifications to Teams see https://github.com/sjkp/Microsoft-teams-docs/blob/master/teams/connectors.md
I've already added the webhook URL as a secret to the repository.
