### ISSUE TITLE
Remove deploy build

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#448]
When #408 has been merged, local development will be much easier, so we can think about removing the develop build and renaming the develop branch.

**Comment by martvanrijthoven** [comment]
develop branch was also created to show and discuss new features and new designs with non-webteam members (e.g. other staff members). But it has not been used very actively so might indeed could be removed.

**Comment by nlessmann** [comment]
Joey will have a look, we will discuss this again in the next meeting.

**Comment by JoeySpronck** [comment]
Successfully removed the development website
