### ISSUE TITLE
Do not deploy websites without changes

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#45]
Pelican updates a timestamp in the sitemap on each build. This results in a new deploy for each website even when nothing was changed (for that particular website).

**Comment by GeertLitjens** [comment]
I also made a change to my personal page which is not deployed, so maybe something else is also going on?

**Comment by wouterbulten** [comment]
Yes that was caused by the build script breaking on a git push. That's fixed now. You can always check the build here to see if your commit was successful: https://travis-ci.org/DIAGNijmegen/website-content

**Comment by wouterbulten** [comment]
Removed the feed generation for now as we are not actively using it.
