### ISSUE TITLE
Add links to papers distributed via the Radboud Repository (Taverne)

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#451]
Example: https://repository.ubn.ru.nl/handle/2066/235298

**Comment by JasperLinmans** [comment]
Lacking a API this would require building a scraper, also compatible with difficult characters in either author names or paper titles. As discussed during the meeting, leaving this for now to work on more timely issues.

**Comment by JoeySpronck** [comment]
Rough steps to tackle issue: 
- Search for papers by directly editing the search url
- Inspect html, check matches for search (titles could be slightly different)
- Inspect link from best match, check title, first author
- On this page we could additionally check the linked DOI whether it contains right title/authors
- Return url from correct match

**Comment by keelinm** [comment]
Question for @martvanrijthoven : Adding the button on the website - should it be in templates/publication.html as well as templates/blocks/publication_item.html

**Comment by keelinm** [comment]
Clarification from Mart - publication_item is an item in a list (and the button for Download appears under it), while publication is the page that is just for a single publication (what you get if you click on the abstract button).  The buttons appear on both the list and the individual page.
