### ISSUE TITLE
Setup breast imaging website

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#46]

**Comment by wouterbulten** [comment]
@martvanrijthoven  aiimnijmegen.nl should be the domain name for this website. @jonasteuwen can supply you with more info/credentials.

**Comment by jonasteuwen** [comment]
What credentials do you need? Could it have two domains? aiimnijmegen.nl or breastimaging.nl (both mine).

**Comment by wouterbulten** [comment]
One has to be the main domain (that also shows up in search engines), the other can forward to the main one.

**Comment by jonasteuwen** [comment]
Alright. Then aiimnijmegen.nl

**Comment by martvanrijthoven** [comment]
@jonasteuwen 

Can you supply me with the information that i need for the dns management? Thanks!

**Comment by wouterbulten** [comment]
Note: don't add it to the issue, send it to Mart personally. This repo is public.

**Comment by wouterbulten** [comment]
The website is online. Closing this issue.
