### ISSUE TITLE
Profile pages show also completed projects

### ISSUE THREAD

**Issue by nlessmann** [DIAGNijmegen/website-content#460]
The profile page of a member lists projects, and these currently include completed projects. We need to discuss whether this is the intended behavior and if not implement a fix.

**Comment by nlessmann** [comment]
The "Projects" page (on the CPG website) splits the projects up into running and finished projects.

The research line pages (on the DIAG website) are manually configured because there is no relationship between projects and research lines - a project lists the people that are involved but not to which research line it belongs. Instead, the research line page lists the projects that belong to the line.

Considerations:
* If we eventually replace the "Projects" page on the CPG website with a "Research" page, there could be project pages that cannot be reached anymore. Should we add a feature to the research line pages to show finished projects under a separate header?
* On a profile page, we could do the same - either not show finished projects or list them below the running projects as "Past projects" or similar.

**Comment by JasperLinmans** [comment]
There are only a few people in our group (staff members) that stay long enough to create an enormous backlog of old projects, and maybe some would actually still like to showcase finished projects. So I agree, having it optional in some way is probably best.

**Comment by JasperLinmans** [comment]
Discussed during the meeting:
- Make every item (projects, software, algorithms, etc.) on the member page optional, and configurable in the markdown file. 
- Think about which sections exactly (algorithms is currently not implemented). 
- Make a split between running and past projects. This way, everyone can hide past projects if desired.

**Comment by keelinm** [comment]
Marina would add code so that there would be headers dividing completed projects from running projects

**Comment by keelinm** [comment]
Fixed by Marina
