### ISSUE TITLE
CARA lab website

### ISSUE THREAD

**Issue by marinadamato** [DIAGNijmegen/website-content#522]
Jos asked us to create a new website for CARA lab. The website should have a different style (it's not a Radboudumc website) but some overlap in terms of content (members, vacancies, news, etc.). 

Issues:
- how to manage members: there are some members who were previously part of DIAG or external members
- how to manage publications: we cannot assume that every publication is related to DIAG

**Comment by marinadamato** [comment]
@keelinm can I close this issue?

**Comment by keelinm** [comment]
yes, closing.
