### ISSUE TITLE
links on former members pages not always available

### ISSUE THREAD

**Issue by keelinm** [DIAGNijmegen/website-content#526]
The former members page currently shows a link for each member name that should direct to their linkedin page.  If no linkedin page was given or could be found then this link just reloads the former members list page (i.e. does nothing).  It would be neater to have some logic to ensure that the member name is shown without any hyperlink if none is available.

**Comment by marinadamato** [comment]
I implemented the second solution: when there is no linkedin page associated to the member, than the member name is shown without any hyperlink (see the list of former employees on the DIAG website). Is this what we want? If so, we can close the issue.

**Comment by keelinm** [comment]
yes to the comment above! closing this as resolved.
