### ISSUE TITLE
GC cards fail in github actions

### ISSUE THREAD

**Issue by martvanrijthoven** [DIAGNijmegen/website-content#528]
while building the websites and requesting info to create the GC cards, the .json() fails:
e.g.:

https://github.com/DIAGNijmegen/website-content/actions/runs/5241360202/jobs/9463352361#step:7:500

However this works perfectly fine locally

**Comment by martvanrijthoven** [comment]
relevant code: https://github.com/DIAGNijmegen/website-content/blob/e3a9deddd60ae169783c4b81e025dce61877b3ab/plugins/inline_extend/inline.py#L99

**Comment by jmsmkn** [comment]
I think that it should be fixed, could you try again?

**Comment by martvanrijthoven** [comment]
Yes works now again, Thanks!
