### ISSUE TITLE
Author middle initials are not displayed in publication list

### ISSUE THREAD

**Issue by keelinm** [DIAGNijmegen/website-content#538]
Joeran Bosma raised the issue that his publications list him as J. Bosma not J. S. Bosma as is his preference.  This is the case for all authors, even if middle initials are entered in the bib file they are not displayed on the website. 
Need to investigate why it is implemented like this and whether it can be fixed so that if the bib entry has middle initials then these would be displayed.

**Comment by drepeeters** [comment]
This issue is fixed using a name mapping for authors that want to display their name other than our conventional way of displaying author names.
