### ISSUE TITLE
Error: site not found

### ISSUE THREAD

**Issue by marinadamato** [DIAGNijmegen/website-content#561]
The deployment on netlify is no longer working. When we run the github action, we encounter the following error for every website: 

`Error: Site not found. Please rerun "netlify link"`

We attempted to resolve the issue by updating the secrets of the site IDs, but unfortunately, it did not resolve the problem.

Last week, the SSL certificate update failed and we had to update it manually. Also, we updated the email account and password on Netlify. We are not sure if these changes are related to the current issue. 

@martvanrijthoven sorry to bother you, but do you have any insights on the potential cause and how we might address this problem?"

**Comment by martvanrijthoven** [comment]
Dear Marina,

I have some time tomorrow around 11 to have a look together. Would that work for you?

**Comment by marinadamato** [comment]
Yes, that would be great, thanks Mart!

**Comment by martvanrijthoven** [comment]
Hi,

Just something that I thought of: you maybe have an easier time to debug the issue when tryin to deploy the site locally without github actions. You just have to have an updated version of the repo locally and then you can try to run the commands that are used in the github workflow

**Comment by marinadamato** [comment]
The issues has been resolved by updating the netlify auth token.
