### ISSUE TITLE
Extend available formats thesis cover

### ISSUE THREAD

**Issue by marinadamato** [DIAGNijmegen/website-content#568]
The covers are correctly displayed on the website only if they are saved as .png images. We should change the scripts so they can also accept covers saved as jpg/jpeg.

**Comment by marinadamato** [comment]
The `bibreader` scripts assumes that the cover format is .png and the extension is hard-coded: see [here](https://github.com/DIAGNijmegen/website-content/blob/3525df404e9032504d87af46317ac0d8124621cd/bibliography/bibreader.py#L257). I'm not sure how difficult it would be to update this (and possibly other scripts?), and honestly I think this is very low priority, so it might not even make sense to address this issue. @michellestegem @drepeeters what do you think?

**Comment by drepeeters** [comment]
You could adjust the documentation that the thesis cover to be in ".png" format. This should be good enough for now, and we can later look at other code that may depend on the ".png" format.

**Comment by marinadamato** [comment]
I will close this issue for now as it's not a priority at the moment. I adjusted the documentation that the thesis cover has to be in ".png" format.
