### ISSUE TITLE
Publications pipeline does not work with python 3.7

### ISSUE THREAD

**Issue by ghumpire** [DIAGNijmegen/website-content#58]
Describe your issue here.
The publications pipeline does not work with Python >= 3.7, this issue was reproduced on Windows (Ajay) and Linux (Mart). 

@martvanrijthoven Please report here the full error you got to keep track of it.

**Comment by martvanrijthoven** [comment]
I can not reproduce this error anymore. It seems that it is fixed. I close this issue for know. We can reopen if the issue occurs again.
