### ISSUE TITLE
Hide empty blocks on list pages

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/website-content#6]
Eg, on this page https://rse.diagnijmegen.nl/members/ the Scientific staff, Visiting researcher and Former members sections are empty, would be good to hide those headings.

**Comment by wouterbulten** [comment]
@jmsmkn I just saw that you have an active branch on this. I added Mart as the assignee as it would be a nice issue for him to start on. But if you are working on this already he can work on something else.

**Comment by jmsmkn** [comment]
Sorry - I want to make the rse website public and this is blocking it...

**Comment by jmsmkn** [comment]
The only block that needs to be hidden for RSE now is Projects on the home page, can you do this @martvanrijthoven ? Thanks!
