### ISSUE TITLE
New website for neuro group

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#60]
We need to set up a new website for the neuro group. Meyke will have the first meeting.

**Comment by MeykeHermsen** [comment]
Rashindra will brainstorm with his group about the domain name and forward the decision to us. Mart can subsequently set up the template. Kevin shall be responsible for the content of their website.

**Comment by rashindra** [comment]
Thanks! We haven't decided yet on a domain-name but is it possible to setup the website already (e.g. diagnijmegen.nl/neuro for now?). Sil will also be involved mainly to cover the stroke (software) results so far.

**Comment by wouterbulten** [comment]
Website is live at https://diagnijmegen.github.io/website-neuro/

**Comment by rashindra** [comment]
Thanks! I was wondering whether we should be able to do the following ourselves or if this is something that should be requested here: I'd like to have a separate button on top named Software, next to Project button (both folded out).

**Comment by wouterbulten** [comment]
You can set it up yourself but we can also make the initial setup. You can then always change it later if you want. 

To make room for a "Software" menu item you will need to remove one of the others. What would you like the menu to be?

**Comment by wouterbulten** [comment]
To add: software is currently also displayed on the "Projects" page.

**Comment by rashindra** [comment]
Please hide Project and Vacancies and show/fold-out Publication and Software. Also, I'd like to change Members to People

**Comment by wouterbulten** [comment]
I've updated the menu. We currently chose for "Members" for all websites and this is currently not configurable. If this is really desirable we need to make a feature for this.

I've kept presentations in there. See https://www.computationalpathologygroup.eu/presentations/ for an example how the pathology group uses that.

**Comment by wouterbulten** [comment]
To clarify: You can change the menu name from "members" to "people" but the url will stil be /members

**Comment by wouterbulten** [comment]
The website is online so I'm closing this issue.

@rashindra let us know when you want to change the domain name of the website. Then we'll configure it.
