### ISSUE TITLE
4 months old md file not used on website

### ISSUE THREAD

**Issue by RitaBylsma** [DIAGNijmegen/website-content#63]
**Describe the bug**
Searching for 'art' or 'iefers' on http://radboudimaging.nl/index.php/People does not give a hit on Bart Liefers, while bart-liefers.md exists on https://github.com/DIAGNijmegen/website-content/tree/master/content/pages/members and is 4 months old.

**To Reproduce**
1. Open Firefox under Xubuntu Linux
2. See above

**Comment by jmsmkn** [comment]
The content for radboudimaging.nl does not come from this repo - they're separate systems right now. Eventually, the web team would like to have radboudimaging.nl based on this content but I think that it will be a while before it is implemented.
