### ISSUE TITLE
Blurry images theses gallery and placeholder picture members

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#64]
Please load higher resolution versions of the thesis covers and member placeholder

**Comment by wouterbulten** [comment]
Can we upload higher resolution images of the thesis covers?

**Comment by ghumpire** [comment]
The covers we have on Github are the high resolution, I think. Just double checking, the DIAG website has the same image resolution as the cover we have on Github:
- DIAG website: http://diagnijmegen.nl/index.php/Publication?bibkey=Bejn17a
- Github repo: https://github.com/DIAGNijmegen/website-content/blob/master/content/images/theses/Bejn17a.png (226kb)

but it looks blurry only in the Computational Pathology website: https://www.computationalpathologygroup.eu/thesis-gallery/ If you download https://www.computationalpathologygroup.eu/images/theses/Bejn17a.png you will notice it is 30kb and 160x226 pixels, the original one (on Github) is 226kb and 283x400. So, some compression+re-scaling is involved here.

**Comment by MeykeHermsen** [comment]
Yes, it is somewhere coded in what resolution the images are displayed in which section and I think that for the thesis gallery this is now set too small.

**Comment by wouterbulten** [comment]
It is a combination of two things: a low resolution source image (also on diagnijmegen.nl) and how the script handles this.

Currently, the optimize script looks for the closest size that it can resize the image to:

```js
const outputSizes = [160, 320, 480, 768, 1024];
```
 The images on diagnijmegen are only 283 pixels wide so they are mapped to the closest width in our script (which is 160 pixels). If we would upload higher resolution images (say 400 pixels wide) then they will be mapped to a larger image (320 pixels in this example). 

A workaround is to load the original full image, but then this has to be changed in the template which is less desirable. We should have the original thesis images somewhere right? Uploading a larger version would solve the issue automatically.

**Comment by wouterbulten** [comment]
Can we close this issue? I think it is fixed by uploading higher resolution images.

**Comment by MeykeHermsen** [comment]
Yes, we can close it. I will upload the original files.
