### ISSUE TITLE
Wrong url on thesis pages

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#65]
**Describe the bug**
The URL buttons on the thesis pages refer to non-existent pages. For example: https://www.computationalpathologygroup.eu/publications/bejn17a/ The url button links to https://www.computationalpathologygroup.eu/publications/bejn17a/publications/bejn17a/

@ghumpire Do you have an idea what could cause this?

(Found by @JMBokhorst)

**Comment by ghumpire** [comment]
This is fixed now. The problem was in the thesis template, which was pointing to page.url (taken by Pelican) instead of page.urlweb (defined by me). Now, it works fine.

**Comment by wouterbulten** [comment]
Thanks for the quick fix!
