### ISSUE TITLE
Duplicate publications

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#71]
**Describe the bug**
See for example:

https://diagnijmegen.github.io/website-neuro/publications/rashindra-manniesing/

There are duplicate publications on the page. 
![image](https://user-images.githubusercontent.com/2886251/61360252-5b24e100-a87e-11e9-89b0-6eeda3aafaf2.png)

**Comment by ghumpire** [comment]
This is fixed now, see https://diagnijmegen.github.io/website-neuro/publications/rashindra-manniesing/
