### ISSUE TITLE
Incorrect journal title on publication page

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#72]
**Describe the bug**

See https://diagnijmegen.github.io/website-neuro/publications/rashindra-manniesing/

![image](https://user-images.githubusercontent.com/2886251/61360436-b7880080-a87e-11e9-95fb-2711402394ce.png)

**Comment by ghumpire** [comment]
The journal field of Pate19 in diag.bib is set to "_IEEE_Access_" which was not defined at the top of the diag.bib. For now, I fixed this as a workaround by removing the underscores. I believe _IEEE_Access_ should not be in the journal field of that bibentry, it should be something like "IEEEACCESS" to follow the same pattern as other Journals/conferences that were defined at the top of diag.bib, for instance, MICCAI, SPIE, etc. The proper solution would be adding IEEEACCESS  to the top of diag.bib, not sure why Ajay did not do it, is there may be a restriction?

**Comment by ghumpire** [comment]
This should be fixed after building the website.

**Comment by ghumpire** [comment]
Fixed via 69dac30 and b38d0aa

**Comment by ghumpire** [comment]
See: https://diagnijmegen.github.io/website-neuro/publications/pate19/
