### ISSUE TITLE
Optional year-headings in publication lists

### ISSUE THREAD

**Issue by rashindra** [DIAGNijmegen/website-content#73]
Would be nice to be able to turn-off the year headings in a publication list (e.g. http://www.diagnijmegen.nl/index.php/PublicationsAuthor?author=R._Manniesing&fullname=Rashindra+Manniesing&yearheadings=0)

**Comment by martvanrijthoven** [comment]
Will be done site-wide using a config variable.

**Comment by wouterbulten** [comment]
Increasing the priority of this issue to medium. It's probably not enough to do this site-wide. Instead we will have to generate a new page, or do something with javascript to remove/hide the headings. 

Maybe we can have two pages:

1. https://www.computationalpathologygroup.eu/publications/jeroen-van-der-laak/
2. https://www.computationalpathologygroup.eu/publications/jeroen-van-der-laak/all

**Comment by martvanrijthoven** [comment]
Implemented the option to specify SHOW_PUBLICATION_YEARS in the pelicanconfig for showing/not showing years for the publication page of the group. Furthermore members/people can specify show_publication_years in the .md files for showing/not showing years on the authors publication page. I am leaving this issue open until i have updated the documentation.

**Comment by wouterbulten** [comment]
@martvanrijthoven The flag is a nice addition. But also see my previous comment. We will need both pages probably for each user. Would that be possible? I think its cleanest to just generate a new page without the headings.

**Comment by martvanrijthoven** [comment]
Thanks! Yes i agree with you that if we want to have both views available at the same time it is cleaner to have two pages. But i am confused about the use-case. When/Where do you link to one of them? If I understand correctly, on the diagnijmegen.nl everyone has a preference and you can only switch between views via the URL itself. If this is true, the page with the preference will be sufficient. But maybe i am missing another use-case?

**Comment by martvanrijthoven** [comment]
I kept the option for users and sites to specify their preferences. I added the /all page which always shows all publications without year headings. However it may be confusing as the 'all' button on pages where year headings are enabled switches between single years and all years (both with year headings). @wouterbulten  should we create another button that redirects to the /all page?

**Comment by wouterbulten** [comment]
Thanks Mart!

How much additional code do we need to have in the templates to keep the preferences for users/sites in?

I think the /all is mostly used by users themselves, and is less for visitors. For now I think we can keep it outside of the menu and see if there is a need for it later on. People could for example add link in their bio "full list of all publications here".

**Comment by martvanrijthoven** [comment]
The logic for /all and the preference for users/site page is the same, (i.e., the /all page uses the same template) so essentially the preference option does not include additional code.

Ok lets keep the /all page outside of the menu for now. Thanks!

**Comment by martvanrijthoven** [comment]
TODO update documentation
