### ISSUE TITLE
Incorrect name matching for publications

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#77]
**Describe the bug**

See publication pages of Midas:

- Old: http://www.diagnijmegen.nl/index.php/PublicationsAuthor?author=!M._Meijs&fullname=Midas+Meijs
- New: https://diagnijmegen.github.io/website-neuro/publications/midas-meijs/

To many publications are included as there is someone with the same name. On the old website this was fixed by settings a explicit name (e.g. !M._Meijs).

**Comment by wouterbulten** [comment]
@bjliefers I think this is part of your bibtex parser right? Or @ghumpire do we need to fix this in our pelican plugin?

**Comment by ghumpire** [comment]
This is part of our pelican plugin. I will try to fix it out today.

**Comment by bjliefers** [comment]
I remember we discussed this issue when setting up the new website. I think we agreed back then on a solution where we would maintain a list of bibkeys to exclude for a certain employee. That would be more manageable in the long term than the current solution in the old website. There they add complex rules about how strict to check initials etc, but in practice there were still some incorrect matches that couldn't be caught by such a filter (e.g. some other A. Patel that is not Ajay)

**Comment by ghumpire** [comment]
The old publications pipeline needed rules like !M._Meijs to prevent this issue. Luckily, after parsing the diad.bib, Bart's script returns the full first name and last names of all the authors, which easily fixed this issue. For instance, for a bib entry with the author 'Anup Patel':
- The old publications pipeline would have post-processed it as 'A Patel' matching 'Ajay Patel'
- The new publications pipeline gets the full name ('Anup Patel') and matches the first name + last names. So, publications of 'Anup Patel' won't be assigned to 'Ajay Patel'.

I checked the list of publication of some people and looks everything fine. I just had problems with Jeroen's publications (Jeroen AWM van der Laak, J A W M van der Laak, JW van der Laak, J A van der Laak, and so on) but that's fixed now. 

After the commits above, Ajay, Midas, and Jeroen got the correct list of publications. I could not check the publications of everyone but this seems to work, if this is not the solution, then maybe we should go for what Bart mentioned in the previous comment.

**Comment by wouterbulten** [comment]
The new name matching sounds good!

Babaks thesis has disappeared from the website. Could this be related? (found by @MeykeHermsen )

**Comment by ghumpire** [comment]
Thanks @MeykeHermsen for finding this. Indeed, this was related to my last changes. The problem was how Babak's names appear in the bib file 'B.Ehteshami Bejnordi' which usually should be 'Babak Ehteshami Bejnordi' or 'Bejnordi, B. Ehteshami'. I fixed that in my last commit and now Babak is back to the hall-of-fame :) https://www.computationalpathologygroup.eu/thesis-gallery/

**Comment by wouterbulten** [comment]
Thanks for fixing this! Will close the issue, we can reopen if new problems emerge.
