### ISSUE TITLE
RSE website needs new social sharing image

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/website-content#78]
Go to https://cards-dev.twitter.com/validator and enter https://rse.diagnijmegen.nl 

The rendered card will have a pathology image and a description of the pathology group. Probably this needs to be updated in the RSE pelican configuration file.

**Comment by wouterbulten** [comment]
Yes indeed. Pages that do not have their own main image will use the SITE_IMAGE: https://github.com/DIAGNijmegen/website-content/blob/master/website-rse/pelicanconf.py#L20

**Comment by wouterbulten** [comment]
Meyke has replaced the pathology image with a placeholder.

**Comment by jmsmkn** [comment]
Thanks! We still need to put an image up there for us so re-opening this. It's already in the rse development project, let me know if there is a better place to create content issues that we will solve.

**Comment by wouterbulten** [comment]
It's fine to put it here, especially if it has the content tag.

**Comment by martvanrijthoven** [comment]
Can this issue be closed?
