### ISSUE TITLE
Breadcrumbs missing from Publications and Thesis Gallery pages

### ISSUE THREAD

**Issue by jmsmkn** [DIAGNijmegen/website-content#8]

**Comment by wouterbulten** [comment]
Could you give an example where this goes wrong?

It's working on the CPG website: https://www.computationalpathologygroup.eu/publications/pinc19/

**Comment by jmsmkn** [comment]
https://rse.diagnijmegen.nl/thesis-gallery/ and https://rse.diagnijmegen.nl/publications/

Maybe because they're empty for RSE? Might be solved with #9

**Comment by jmsmkn** [comment]
Scratch that - it's the same here:  https://www.computationalpathologygroup.eu/publications/

**Comment by wouterbulten** [comment]
No you're right. They are missing on the index pages.

**Comment by martvanrijthoven** [comment]
Breadcrumbs added to the pages
