### ISSUE TITLE
abstract is not shown correctly

### ISSUE THREAD

**Issue by rashindra** [DIAGNijmegen/website-content#83]
**Describe the bug**
For example: https://diagnijmegen.github.io/website-neuro/publications/kosc18/

According to Kevin, it seems related to the use of curly braces in the bibtex entry

**To Reproduce (if applicable)**

**Screenshots (if applicable)**

**Device information**
If applicable, on which device(s) does the problem occur?

**Additional context**

**Comment by kevin-kos** [comment]
Was just writing the issue myself, so I'll just copy my text:

We found some publications where the abstracts are not properly displayed, e.g. text stops in the middle of the abstract.
Examples:
https://diagnijmegen.github.io/website-neuro/publications/kosc18/
https://diagnijmegen.github.io/website-neuro/publications/meij18b/

I checked the publications in question in jabref, and to me it seems to be related to the usage of curly brackets {} in the abstract description. Although I only checked a few so the problem might be something else.

Can this be fixed, or is this behavior expected and we should change all abstracts to not have curly brackets in their desciption?

**Comment by wouterbulten** [comment]
@MeykeHermsen you are cleaning up the .bib file for DIAG. Is this something you also address?

**Comment by ghumpire** [comment]
The problem was a mix of two things in the bibentry:
- Multiline abstract 
- Curly braces

Previously, the plugin handled both cases separately, my last commit should fix this issue.

**Comment by wouterbulten** [comment]
Nice, thanks for fixing!
