### ISSUE TITLE
Reuse highlight style for vacancies on vacancy page

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#88]

**Comment by martvanrijthoven** [comment]
Style for vacancy is now tthe same as highlights. However the text above all vacancies looks a bit off now. Also closed vacancies have to much height in my opinion. I will play around to make it a bit more nice.

**Comment by martvanrijthoven** [comment]
closed vacancies are now in in the old style, added closed no vacancy logic and ad some margins

**Comment by wouterbulten** [comment]
Nice work!
