### ISSUE TITLE
Add support for small news items

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#90]
Items that are smaller than a highlight and only contain a few lines of text.

**Comment by MeykeHermsen** [comment]
This is currently covered by the Twitter feed

**Comment by wouterbulten** [comment]
This is mainly focused on news items for the diag website, like:

> September 12, 2019 - Mehmet Dalmis will defend his PhD thesis with the title' Automated Analysis of Breast MRI: from Traditional Methods into Deep Learning' at 12.30.

This is currently not part of the twitter feed.

**Comment by wouterbulten** [comment]
I don't think there were plans to remove these small items, right? My current plan was to add them below the highlights on the home page.

**Comment by MeykeHermsen** [comment]
The plan was to have these replaced by the tweets, but I agree that this is not used for announcing thesis defends and we do need something for this.  Perhaps we could think of a new format in stead of News and Highlights as for some people it is not clear what exactly the difference is. 
Would it be an idea to add a column left to the Highlights and name this 'Agenda' or something? We can use this for the PhD defenses and other talks (like the open DDH).

**Comment by wouterbulten** [comment]
I agree. Most of the items are agenda-type things. There are a few smaller 'highlight-like' things such as:

> June 28, 2019 - Colin Jacobs and Bram van Ginneken wrote a 'News & Views' item about the Google AI paper on automatic lung cancer detection using deep learning. Check it out here.

Will these be replaced by highlights?

We don't really have place left of the highlights, unless we remove the Twitter feed. Most important thing for now is to decide what kind of content it will be. We can also name it 'updates' internally instead of news? I just need a name to give the content so I can make the directories and such.

**Comment by MeykeHermsen** [comment]
If Mart also agrees I think we can go for Agenda and place this under Highlight. Items such as the News & Views communication could become tweets in the future.

**Comment by martvanrijthoven** [comment]
I agree! Maybe put it above Highlight? because Agenda items does not always have images ( i presume)  and then it will not get enough attention. Highlight always can have an image so it will pop out of the website anyway. Just an idea though?

**Comment by wouterbulten** [comment]
I've made a first version. See https://beta.diagnijmegen.nl/

**Comment by bramvanginneken** [comment]
The idea of the highlight was to have an attractive image centrally on the home page. Otherwise the website opens with the same image always, like the boring one you have now. We are an *image* analysis group so we want to show beautiful images. Like the front page of a newspaper has a different eye catching image/photo every day.

A drawback of the agenda item is that announcements of an upcoming phd defense used to change into a congratulatory message after the defense took place. The does not really work with an agenda. But otherwise announcing things that happen at a certain time and place (always mention the place) makes sense.

**Comment by wouterbulten** [comment]
I would propose to keep the calendar; we can always remove it or change it when needed. It's currently placed below the highlights.

Regarding the home page image: We can experiment with making this dynamic. For example, we could always take the image of the first highlight to give it a more prominent place. We can even make this configurable per subwebsite so that each group can decide. I will make a new issue for that to separate the discussion. See #101

**Comment by wouterbulten** [comment]
Closing this issue, we now have support for a calendar.
