### ISSUE TITLE
Picture external people does not always appear in project page

### ISSUE THREAD

**Issue by MeykeHermsen** [DIAGNijmegen/website-content#91]
The picture of Marcory is missing in https://www.computationalpathologygroup.eu/projects/ami/, while her picture is present in website-content/content/images/people/external/.

For Peter Bult this is not the case: https://www.computationalpathologygroup.eu/projects/prim4bc/

Perhaps this is related to the double last name of Marcory (= van Dijk)?

**Comment by wouterbulten** [comment]
I think the problem here is that the image is to small (140x140) and is therefore skipped by the image pipeline. This is a bug but the best solution for now is to upload a larger image.

**Comment by MeykeHermsen** [comment]
Thank you, uploading a larger file helped. What should be the minimum size?

**Comment by wouterbulten** [comment]
160x160 should work.
