### ISSUE TITLE
Link to project or person without hardcoding path

### ISSUE THREAD

**Issue by jonasteuwen** [DIAGNijmegen/website-content#93]
When writing text in markdown, it might might be better to be able to use [person:Jonas Teuwen] instead of a complete link with [...](...). Same for projects. It would help against dead links.

**Comment by wouterbulten** [comment]
I've made a first implementation of this feature, still in beta-mode. You can do the following:

- `[member: Wouter Bulten]` generates `<a href="/members/wouter-bulten">Wouter Bulten<a>`
- `[member: Wouter Bulten, group: diag]` generates `<a href="https://beta.diagnijmegen.nl/members/wouter-bulten">Wouter Bulten<a>` (where `group` is a valid website identifier). 

The last one is useful for content that is shared between websites.

**Comment by jonasteuwen** [comment]
Thanks, I tried it here: https://www.aiimnijmegen.nl/members/riccardo-samperna/ but does not seem to work. How can I fix it?

**Comment by jonasteuwen** [comment]
Used it now, it does not parse it if you forget to put a space between member: and the name. Is this th wanted behavior?

**Comment by wouterbulten** [comment]
I've updated the regex to:

`\[member:\s*(?P<member>[a-zA-Z\s]+)\s*(,\s*group: (?P<group>[a-zA-Z]+))?\]`

The space is now optional.

**Comment by wouterbulten** [comment]
I've updated the tag. It now automatically links to the default group of that person. (Defined by 'default_group' on the member page). The 'group' can still be overridden if needed.
