### ISSUE TITLE
Hardcoded computational pathology links

### ISSUE THREAD

**Issue by jonasteuwen** [DIAGNijmegen/website-content#94]
- When creating a vacancy and no image is added, automatically an image of computational pathology is shown. Perhaps an image "content here" could be added, it would also force people a bit to make their website look nice.

**Comment by wouterbulten** [comment]
When no image is defined it takes the `SITE_PICTURE`, see https://github.com/DIAGNijmegen/website-content/blob/master/website-aiimnijmegen/pelicanconf.py#L17 You can change that variable to make another default picture for your website. This image is also used for social media sharing if a page does not contain an image. 

Maybe we need to instruct people better to change that variable as we got multiple questions regarding this. 

@MeykeHermsen what do you think? We could replace it with a gray placeholder image like Jonas suggests.

**Comment by MeykeHermsen** [comment]
I think that is a good idea. I will replace this with a placeholder in all the pelican files and note this in de docs.
