### ISSUE TITLE
Projects across organizations do not properly parse bibtex

### ISSUE THREAD

**Issue by jonasteuwen** [DIAGNijmegen/website-content#96]
When a project is shared between groups, such as vph-prism, the bibtex keys only seem to parse when a person writing that paper is associated to that group. A solution might be to suppress those outputs (or just always show all of them). Example: https://www.aiimnijmegen.nl/projects/vphprism/ and https://www.computationalpathologygroup.eu/projects/vphprism/

**Comment by martvanrijthoven** [comment]
I suppressed the publications that are not associated (for now). I think that it makes more sense to show all publications from the project. However, in this case the website should have access to all publications, which is not how the publications generation works at the moment. It will be some work to change this. I keep this issue open for discussion.

**Comment by martvanrijthoven** [comment]
this is solved now
