### ISSUE TITLE
Standardize image paths

### ISSUE THREAD

**Issue by wouterbulten** [DIAGNijmegen/website-content#99]
All content types should have the same way of handling image paths: relative to the images folder. E.g. images for people should be changed from `picture: <image>.png` to `image: people/<image>.png`

**Comment by MeykeHermsen** [comment]
When I change `'images/people/'` into `'images/'` in the code below

   ` {% if person.picture %}
    <a href="{{ person_url }}"><img data-src="{{SITEURL}}/{{ ('images/people/' + person.picture)`

and `picture: <image>.png` to `picture: people/<image>.png` in the member page this does not work.

Do I need to change the code somewhere else as well perhaps?
